In [2]:
import pandas as pd

In [3]:
path = "../data/en.openfoodfacts.org.products.csv"
df = pd.read_csv(path, nrows=200, sep='\t', encoding="utf-8")

In [ ]:
df

,code,url,creator,created_t,created_datetime,last_modified_t,last_modified_datetime,last_modified_by,last_updated_t,last_updated_datetime,...,water-hardness_100g,choline_100g,phylloquinone_100g,beta-glucan_100g,inositol_100g,carnitine_100g,sulphate_100g,nitrate_100g,acidity_100g,carbohydrates-total_100g
0,2,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1760861583,2025-10-19T08:13:03Z,1760861586,2025-10-19T08:13:06Z,NaN,1760861586,2025-10-19T08:13:06Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1752485388,2025-07-14T09:29:48Z,1752485389,2025-07-14T09:29:49Z,NaN,1752485389,2025-07-14T09:29:49Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1768903196,2026-01-20T09:59:56Z,1768903204,2026-01-20T10:00:04Z,NaN,1768903204,2026-01-20T10:00:04Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5,http://world-en.openfoodfacts.org/product/0000...,moon-rabbit,1767072228,2025-12-30T05:23:48Z,1767072233,2025-12-30T05:23:53Z,moon-rabbit,1767072233,2025-12-30T05:23:53Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6,http://world-en.openfoodfacts.org/product/0000...,moon-rabbit,1760212975,2025-10-11T20:02:55Z,1760218930,2025-10-11T21:42:10Z,ascharao,1760218930,2025-10-11T21:42:10Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,203,http://world-en.openfoodfacts.org/product/0000...,foodvisor,1723712059,2024-08-15T08:54:19Z,1736853965,2025-01-14T11:26:05Z,prepperapp,1743604425,2025-04-02T14:33:45Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,204,http://world-en.openfoodfacts.org/product/0000...,prepperapp,1736854059,2025-01-14T11:27:39Z,1736854060,2025-01-14T11:27:40Z,prepperapp,1743601184,2025-04-02T13:39:44Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,205,http://world-en.openfoodfacts.org/product/0000...,date-limite-app,1579948733,2020-01-25T10:38:53Z,1736854137,2025-01-14T11:28:57Z,prepperapp,1743312224,2025-03-30T05:23:44Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,206,http://world-en.openfoodfacts.org/product/0000...,foodless,1714457894,2024-04-30T06:18:14Z,1736854188,2025-01-14T11:29:48Z,prepperapp,1743606871,2025-04-02T15:14:31Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,207,http://world-en.openfoodfacts.org/product/0000...,foodvisor,1658726452,2022-07-25T05:20:52Z,1736854228,2025-01-14T11:30:28Z,prepperapp,1743627070,2025-04-02T20:51:10Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

:

In [ ]:
df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 209 columns):
 #    Column                            Dtype
---   ------                            -----
 0    code                              int64
 1    url                               object
 2    creator                           object
 3    created_t                         int64
 4    created_datetime                  object
 5    last_modified_t                   int64
 6    last_modified_datetime            object
 7    last_modified_by                  object
 8    last_updated_t                    int64
 9    last_updated_datetime             object
 10   product_name                      object
 11   abbreviated_product_name          float64
 12   generic_name                      object
 13   quantity                          object
 14   packaging                         object
 15   packaging_tags                    object
 16   packaging_en                      object
 17   packaging_text                    object
 18   brands                            object
 19   brands_tags                       object
 20   brands_en                         object
 21   categories                        object
 22   categories_tags                   object
 23   categories_en                     object
 24   origins                           object
 25   origins_tags                      object
 26   origins_en                        object
 27   manufacturing_places              object
 28   manufacturing_places_tags         object
 29   labels                            object
 30   labels_tags                       object
 31   labels_en                         object
 32   emb_codes                         object
 33   emb_codes_tags                    object
 34   first_packaging_code_geo          object
 35   cities                            float64
 36   cities_tags                       object
 37   purchase_places                   object
 38   stores                            object
 39   countries                         object
 40   countries_tags                    object
 41   countries_en                      object
 42   ingredients_text                  object
 43   ingredients_tags                  object
 44   ingredients_analysis_tags         object
 45   allergens                         object
 46   allergens_en                      float64
 47   traces                            object
 48   traces_tags                       object
 49   traces_en                         object
 50   serving_size                      object
 51   serving_quantity                  float64
 52   no_nutrition_data                 object
 53   additives_n                       float64
 54   additives                         float64
 55   additives_tags                    object
 56   additives_en                      object
 57   nutriscore_score                  float64
 58   nutriscore_grade                  object
 59   nova_group                        float64
 60   pnns_groups_1                     object
 61   pnns_groups_2                     object
 62   food_groups                       object
 63   food_groups_tags                  object
 64   food_groups_en                    object
 65   states                            object
 66   states_tags                       object
 67   states_en                         object
 68   brand_owner                       float64
 69   environmental_score_score         float64
 70   environmental_score_grade         object
 71   nutrient_levels_tags              object
 72   product_quantity                  float64
 73   owner                             object
 74   data_quality_errors_tags          object
 75   unique_scans_n                    float64
 76   popularity_tags                   object
 77   completeness                      float64
 78   last_image_t                      float64
 79   last_image_datetime               object
 80   main_category                     object
 81   main_category_en                  object
 82   image_url                         object
 83   image_small_url                   object
 84   image_ingredients_url             object
 85   image_ingredients_small_url       object
 86   image_nutrition_url               object
 87   image_nutrition_small_url         object
 88   energy-kj_100g                    float64
 89   energy-kcal_100g                  float64
 90   energy_100g                       float64
 91   energy-from-fat_100g              float64
 92   fat_100g                          float64
 93   saturated-fat_100g                float64
 94   butyric-acid_100g                 float64
 95   caproic-acid_100g                 float64
 96   caprylic-acid_100g                float64
 97   capric-acid_100g                  float64
 98   lauric-acid_100g                  float64
 99   myristic-acid_100g                float64
 100  palmitic-acid_100g                float64
 101  stearic-acid_100g                 float64
 102  arachidic-acid_100g               float64
 103  behenic-acid_100g                 float64
 104  lignoceric-acid_100g              float64
 105  cerotic-acid_100g                 float64
 106  montanic-acid_100g                float64
 107  melissic-acid_100g                float64
 108  unsaturated-fat_100g              float64
 109  monounsaturated-fat_100g          float64
 110  omega-9-fat_100g                  float64
 111  polyunsaturated-fat_100g          float64
 112  omega-3-fat_100g                  float64
 113  omega-6-fat_100g                  float64
 114  alpha-linolenic-acid_100g         float64
 115  eicosapentaenoic-acid_100g        float64
 116  docosahexaenoic-acid_100g         float64
 117  linoleic-acid_100g                float64
 118  arachidonic-acid_100g             float64
 119  gamma-linolenic-acid_100g         float64
 120  dihomo-gamma-linolenic-acid_100g  float64
 121  oleic-acid_100g                   float64
 122  elaidic-acid_100g                 float64
 123  gondoic-acid_100g                 float64
 124  mead-acid_100g                    float64
 125  erucic-acid_100g                  float64
 126  nervonic-acid_100g                float64
 127  trans-fat_100g                    float64
 128  cholesterol_100g                  float64
 129  carbohydrates_100g                float64
 130  sugars_100g                       float64
 131  added-sugars_100g                 float64
 132  sucrose_100g                      float64
 133  glucose_100g                      float64
 134  fructose_100g                     float64
 135  galactose_100g                    float64
 136  lactose_100g                      float64
 137  maltose_100g                      float64
 138  maltodextrins_100g                float64
 139  psicose_100g                      float64
 140  starch_100g                       float64
 141  polyols_100g                      float64
 142  erythritol_100g                   float64
 143  isomalt_100g                      float64
 144  maltitol_100g                     float64
 145  sorbitol_100g                     float64
 146  fiber_100g                        float64
 147  soluble-fiber_100g                float64
 148  polydextrose_100g                 float64
 149  insoluble-fiber_100g              float64
 150  proteins_100g                     float64
 151  casein_100g                       float64
 152  serum-proteins_100g               float64
 153  nucleotides_100g                  float64
 154  salt_100g                         float64
 155  added-salt_100g                   float64
 156  sodium_100g                       float64
 157  alcohol_100g                      float64
 158  vitamin-a_100g                    float64
 159  beta-carotene_100g                float64
 160  vitamin-d_100g                    float64
 161  vitamin-e_100g                    float64
 162  vitamin-k_100g                    float64
 163  vitamin-c_100g                    float64
 164  vitamin-b1_100g                   float64
 165  vitamin-b2_100g                   float64
 166  vitamin-pp_100g                   float64
 167  vitamin-b6_100g                   float64
 168  vitamin-b9_100g                   float64
 169  folates_100g                      float64
 170  vitamin-b12_100g                  float64
 171  biotin_100g                       float64
 172  pantothenic-acid_100g             float64
 173  silica_100g                       float64
 174  bicarbonate_100g                  float64
 175  potassium_100g                    float64
 176  chloride_100g                     float64
 177  calcium_100g                      float64
 178  phosphorus_100g                   float64
 179  iron_100g                         float64
 180  magnesium_100g                    float64
 181  zinc_100g                         float64
 182  copper_100g                       float64
 183  manganese_100g                    float64
 184  fluoride_100g                     float64
 185  selenium_100g                     float64
 186  chromium_100g                     float64
 187  molybdenum_100g                   float64
 188  iodine_100g                       float64
 189  caffeine_100g                     float64
 190  taurine_100g                      float64
 191  methylsulfonylmethane_100g        float64
 192  ph_100g                           float64
 193  fruits-vegetables-legumes_100g    float64
 194  collagen-meat-protein-ratio_100g  float64
 195  cocoa_100g                        float64
 196  chlorophyl_100g                   float64
 197  carbon-footprint_100g             float64
 198  glycemic-index_100g               float64
 199  water-hardness_100g               float64
 200  choline_100g                      float64
 201  phylloquinone_100g                float64
 202  beta-glucan_100g                  float64
 203  inositol_100g                     float64
 204  carnitine_100g                    float64
 205  sulphate_100g                     float64
 206  nitrate_100g                      float64
 207  acidity_100g                      float64
 208  carbohydrates-total_100g          float64
dtypes: float64(135), int64(4), object(70)
memory usage: 326.7+ KB

:

In [ ]:
import pandas as pd
from IPython.display import display

# Affichage complet (sans troncature)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)

# Remplace df par le nom de ton DataFrame si besoin
display(pd.DataFrame({"nom_colonne": df.columns}))

                          nom_colonne
0                                code
1                                 url
2                             creator
3                           created_t
4                    created_datetime
5                     last_modified_t
6              last_modified_datetime
7                    last_modified_by
8                      last_updated_t
9               last_updated_datetime
10                       product_name
11           abbreviated_product_name
12                       generic_name
13                           quantity
14                          packaging
15                     packaging_tags
16                       packaging_en
17                     packaging_text
18                             brands
19                        brands_tags
20                          brands_en
21                         categories
22                    categories_tags
23                      categories_en
24                            origins
25                       origins_tags
26                         origins_en
27               manufacturing_places
28          manufacturing_places_tags
29                             labels
30                        labels_tags
31                          labels_en
32                          emb_codes
33                     emb_codes_tags
34           first_packaging_code_geo
35                             cities
36                        cities_tags
37                    purchase_places
38                             stores
39                          countries
40                     countries_tags
41                       countries_en
42                   ingredients_text
43                   ingredients_tags
44          ingredients_analysis_tags
45                          allergens
46                       allergens_en
47                             traces
48                        traces_tags
49                          traces_en
50                       serving_size
51                   serving_quantity
52                  no_nutrition_data
53                        additives_n
54                          additives
55                     additives_tags
56                       additives_en
57                   nutriscore_score
58                   nutriscore_grade
59                         nova_group
60                      pnns_groups_1
61                      pnns_groups_2
62                        food_groups
63                   food_groups_tags
64                     food_groups_en
65                             states
66                        states_tags
67                          states_en
68                        brand_owner
69          environmental_score_score
70          environmental_score_grade
71               nutrient_levels_tags
72                   product_quantity
73                              owner
74           data_quality_errors_tags
75                     unique_scans_n
76                    popularity_tags
77                       completeness
78                       last_image_t
79                last_image_datetime
80                      main_category
81                   main_category_en
82                          image_url
83                    image_small_url
84              image_ingredients_url
85        image_ingredients_small_url
86                image_nutrition_url
87          image_nutrition_small_url
88                     energy-kj_100g
89                   energy-kcal_100g
90                        energy_100g
91               energy-from-fat_100g
92                           fat_100g
93                 saturated-fat_100g
94                  butyric-acid_100g
95                  caproic-acid_100g
96                 caprylic-acid_100g
97                   capric-acid_100g
98                   lauric-acid_100g
99                 myristic-acid_100g
100                palmitic-acid_100g
101                 stearic-acid_100g
102               arachidic-acid_100g
103                 behenic-acid_100g
104              lignoceric-acid_100g
105                 cerotic-acid_100g
106                montanic-acid_100g
107                melissic-acid_100g
108              unsaturated-fat_100g
109          monounsaturated-fat_100g
110                  omega-9-fat_100g
111          polyunsaturated-fat_100g
112                  omega-3-fat_100g
113                  omega-6-fat_100g
114         alpha-linolenic-acid_100g
115        eicosapentaenoic-acid_100g
116         docosahexaenoic-acid_100g
117                linoleic-acid_100g
118             arachidonic-acid_100g
119         gamma-linolenic-acid_100g
120  dihomo-gamma-linolenic-acid_100g
121                   oleic-acid_100g
122                 elaidic-acid_100g
123                 gondoic-acid_100g
124                    mead-acid_100g
125                  erucic-acid_100g
126                nervonic-acid_100g
127                    trans-fat_100g
128                  cholesterol_100g
129                carbohydrates_100g
130                       sugars_100g
131                 added-sugars_100g
132                      sucrose_100g
133                      glucose_100g
134                     fructose_100g
135                    galactose_100g
136                      lactose_100g
137                      maltose_100g
138                maltodextrins_100g
139                      psicose_100g
140                       starch_100g
141                      polyols_100g
142                   erythritol_100g
143                      isomalt_100g
144                     maltitol_100g
145                     sorbitol_100g
146                        fiber_100g
147                soluble-fiber_100g
148                 polydextrose_100g
149              insoluble-fiber_100g
150                     proteins_100g
151                       casein_100g
152               serum-proteins_100g
153                  nucleotides_100g
154                         salt_100g
155                   added-salt_100g
156                       sodium_100g
157                      alcohol_100g
158                    vitamin-a_100g
159                beta-carotene_100g
160                    vitamin-d_100g
161                    vitamin-e_100g
162                    vitamin-k_100g
163                    vitamin-c_100g
164                   vitamin-b1_100g
165                   vitamin-b2_100g
166                   vitamin-pp_100g
167                   vitamin-b6_100g
168                   vitamin-b9_100g
169                      folates_100g
170                  vitamin-b12_100g
171                       biotin_100g
172             pantothenic-acid_100g
173                       silica_100g
174                  bicarbonate_100g
175                    potassium_100g
176                     chloride_100g
177                      calcium_100g
178                   phosphorus_100g
179                         iron_100g
180                    magnesium_100g
181                         zinc_100g
182                       copper_100g
183                    manganese_100g
184                     fluoride_100g
185                     selenium_100g
186                     chromium_100g
187                   molybdenum_100g
188                       iodine_100g
189                     caffeine_100g
190                      taurine_100g
191        methylsulfonylmethane_100g
192                           ph_100g
193    fruits-vegetables-legumes_100g
194  collagen-meat-protein-ratio_100g
195                        cocoa_100g
196                   chlorophyl_100g
197             carbon-footprint_100g
198               glycemic-index_100g
199               water-hardness_100g
200                      choline_100g
201                phylloquinone_100g
202                  beta-glucan_100g
203                     inositol_100g
204                    carnitine_100g
205                     sulphate_100g
206                      nitrate_100g
207                      acidity_100g
208          carbohydrates-total_100g

:

:

In [ ]:
cols_to_drop = [
    "url", "creator", "created_t", "created_datetime", "last_modified_t",
    "last_modified_datetime", "last_modified_by", "last_updated_t",
    "last_updated_datetime", "abbreviated_product_name", "generic_name",
    "quantity", "brands_tags", "brands_en", "cities", "cities_tags",
    "purchase_places", "stores", "ingredients_analysis_tags", "allergens",
    "allergens_en", "traces", "traces_tags", "traces_en", "serving_size",
    "serving_quantity", "no_nutrition_data", "nova_group", "states",
    "states_tags", "states_en", "brand_owner", "nutrient_levels_tags",
    "product_quantity", "owner", "data_quality_errors_tags", "unique_scans_n",
    "popularity_tags", "completeness", "last_image_t", "last_image_datetime",
    "main_category", "main_category_en", "image_url", "image_small_url",
    "image_ingredients_url", "image_ingredients_small_url",
    "image_nutrition_url", "image_nutrition_small_url", "energy-from-fat_100g",
    "butyric-acid_100g", "caproic-acid_100g", "caprylic-acid_100g",
    "capric-acid_100g", "lauric-acid_100g", "myristic-acid_100g",
    "palmitic-acid_100g", "stearic-acid_100g", "arachidic-acid_100g",
    "behenic-acid_100g", "lignoceric-acid_100g", "cerotic-acid_100g",
    "montanic-acid_100g", "melissic-acid_100g", "unsaturated-fat_100g",
    "monounsaturated-fat_100g", "omega-9-fat_100g", "polyunsaturated-fat_100g",
    "omega-3-fat_100g", "omega-6-fat_100g", "alpha-linolenic-acid_100g",
    "eicosapentaenoic-acid_100g", "docosahexaenoic-acid_100g",
    "linoleic-acid_100g", "arachidonic-acid_100g",
    "gamma-linolenic-acid_100g", "dihomo-gamma-linolenic-acid_100g",
    "oleic-acid_100g", "elaidic-acid_100g", "gondoic-acid_100g",
    "mead-acid_100g", "erucic-acid_100g", "nervonic-acid_100g",
    "trans-fat_100g", "cholesterol_100g", "added-sugars_100g",
    "sucrose_100g", "glucose_100g", "fructose_100g", "galactose_100g",
    "lactose_100g", "maltose_100g", "maltodextrins_100g", "psicose_100g",
    "starch_100g", "polyols_100g", "erythritol_100g", "isomalt_100g",
    "maltitol_100g", "sorbitol_100g", "soluble-fiber_100g",
    "polydextrose_100g", "insoluble-fiber_100g", "casein_100g",
    "serum-proteins_100g", "nucleotides_100g", "added-salt_100g",
    "alcohol_100g", "vitamin-a_100g", "beta-carotene_100g", "vitamin-d_100g",
    "vitamin-e_100g", "vitamin-k_100g", "vitamin-c_100g", "vitamin-b1_100g",
    "vitamin-b2_100g", "vitamin-pp_100g", "vitamin-b6_100g", "vitamin-b9_100g",
    "folates_100g", "vitamin-b12_100g", "biotin_100g",
    "pantothenic-acid_100g", "silica_100g", "bicarbonate_100g",
    "potassium_100g", "chloride_100g", "calcium_100g", "phosphorus_100g",
    "iron_100g", "magnesium_100g", "zinc_100g", "copper_100g",
    "manganese_100g", "fluoride_100g", "selenium_100g", "chromium_100g",
    "molybdenum_100g", "iodine_100g", "caffeine_100g", "taurine_100g",
    "methylsulfonylmethane_100g", "ph_100g",
    "collagen-meat-protein-ratio_100g", "cocoa_100g", "chlorophyl_100g",
    "glycemic-index_100g", "water-hardness_100g", "choline_100g",
    "phylloquinone_100g", "beta-glucan_100g", "inositol_100g",
    "carnitine_100g", "sulphate_100g", "nitrate_100g", "acidity_100g",
    "carbohydrates-total_100g"
]

df = df.drop(columns=cols_to_drop)

:

:

In [ ]:
df

,code,product_name,packaging,packaging_tags,packaging_en,packaging_text,brands,categories,categories_tags,categories_en,origins,origins_tags,origins_en,manufacturing_places,manufacturing_places_tags,labels,labels_tags,labels_en,emb_codes,emb_codes_tags,first_packaging_code_geo,countries,countries_tags,countries_en,ingredients_text,ingredients_tags,additives_n,additives,additives_tags,additives_en,nutriscore_score,nutriscore_grade,pnns_groups_1,pnns_groups_2,food_groups,food_groups_tags,food_groups_en,environmental_score_score,environmental_score_grade,energy-kj_100g,energy-kcal_100g,energy_100g,fat_100g,saturated-fat_100g,carbohydrates_100g,sugars_100g,fiber_100g,proteins_100g,salt_100g,sodium_100g,fruits-vegetables-legumes_100g,carbon-footprint_100g
0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en:Germany,en:germany,Germany,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en:France,en:france,France,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en:france,en:france,France,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en:France,en:france,France,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en:Germany,en:germany,Germany,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6666,6666,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Germany, en:france","en:france,en:germany","France,Germany",NaN,NaN,NaN,NaN,NaN,NaN,NaN,unknown,unknown,unknown,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,granola Bio le Chocolaté,NaN,NaN,NaN,NaN,Mg ricarica,"Aliments et boissons à base de végétaux, Aliments d'origine végétale, Aliments à base de fruits et de légumes, Fruits et produits dérivés, Produits déshydratés, Aliments à base de plantes séchées, Fruits secs","en:plant-based-foods-and-beverages,en:plant-based-foods,en:fruits-and-vegetables-based-foods,en:dried-products,en:fruits-based-foods,en:dried-plant-based-foods,en:dried-fruits","Plant-based foods and beverages,Plant-based foods,Fruits and vegetables based foods,Dried products,Fruits based foods,Dried plant-based foods,Dried fruits",NaN,NaN,NaN,NaN,NaN,en:made-in-france,en:made-in-france,Made in France,NaN,NaN,NaN,"Spanien, Germany","en:germany,en:spain","Germany,Spain",HONIG stillende Frauen nicht geeignet. D bestrahlung vermeiden und be trocken lagern. X000V0XH07,"es:honig-stillende-frauen-nicht-geeignet,es:d-bestrahlung-vermeiden-und-be-trocken-lagern,es:x000v0xh07",0.0,NaN,NaN,NaN,4.0,c,Fruits and vegetables,Dried fruits,en:dried-fruits,"en:fruits-and-vegetables,en:dried-fruits","Fruits and vegetables,Dried fruits",NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,NaN,NaN,NaN,NaN,NaN,Zuegg,Cornish clotted cream shortbread,en:cornish-clotted-cream-shortbread,Cornish-clotted-cream-shortbread,NaN,NaN,NaN,NaN,NaN,"Halal, No added sugar, No lactose, en:no-gluten","en:no-gluten,en:halal,en:no-added-sugar,en:no-lactose","No gluten,Halal,No added sugar,No lactose",NaN,NaN,NaN,"Vereinigte Staaten von Amerika, Germany","en:germany,en:united-states","Germany,United States","Sojaproteinisolat, Weizen - protein, Kaffee-Extrakt (6 %), Reisprotein, Erbsenprotein - isolat, Kakaopulver stark ent - ölt, Sonnenblumenprotein, Mandelprotein, Aroma, Sü - Bungsmittel (Sucralose).","en:soy-protein-isolate,en:protein,en:plant-protein,en:soy-protein,en:wheat-protein,en:coffee,en:rice-protein,en:pea-protein,de:isolat,de:kakaopulver-stark-ent,de:ölt,en:sunflower-protein,en:almond-protein,en:flavouring,de:sü,de:bungsmittel,en:e955",1.0,NaN,en:e955,E955 - Sucralose,6.0,c,unknown,unknown,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,Protein Plant Powered Wrap,NaN,NaN,NaN,NaN,Mission,"Sandwiches, Wraps, Protein","en:sandwiches,en:wraps,en:protein","Sandwiches,Wraps,Protein",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"en:germany, World","en:germany,en:world","Germany,World",NaN,NaN,NaN,NaN,NaN,NaN,NaN,unknown,Composite foods,Sandwiches,en:sandwiches,"en:composite-foods,en:sandwiches","Composite foods,Sandwiches",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9,xytitol pastilles,NaN,NaN,NaN,NaN,xylimgxyling,"it:Gestione sovrappeso, it:obesità, Wrap","en:sandwiches,en:wraps,it:gestione-sovrappeso,it:obesita","Sandwiches,Wraps,it:gestione-sovrappeso,it:obesita",NaN,NaN,NaN,NaN,NaN,"Organic, Vegetarian, EU Organic, Vegan, DE-ÖKO-006, en:made-in-france","en:organic,en:vegetarian,en:eu-organic,en:vegan,en:de-oko-006,en:made-in-france","Organic,Vegetarian,EU Organic,Vegan,DE-ÖKO-006,Made in France",NaN,NaN,NaN,"Germany,Spain","en:germany,en:spain","Germany,Spain",NaN,NaN,NaN,NaN,NaN,NaN,-11.0,a,Composite foods,Sandwiches,en:sandwiches,"en:composite-foods,en:sandwiches","Composite foods,Sandwiches",NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,10,xxx,"Plastic,Cardboard,fr:Boîte en carton,fr:Film en plastique","en:plastic,en:cardboard,fr:boite-en-carton,fr:film-en-plastique","Plastic,Cardboard,fr:boite-en-carton,fr:film-en-plastique",NaN,xxx,"Beverages and beverages preparations, Beverages, Snacks, Desserts, Sweet snacks, Biscuits and cakes, Biscuits and crackers, Biscuits, Cakes, Pound Cake, Madeleines, Plain madeleines","en:beverages-and-beverages-preparations,en:beverages,en:snacks,en:desserts,en:sweet-snacks,en:biscuits-and-cakes,en:biscuits-and-crackers,en:biscuits,en:cakes,en:pound-cake,en:madeleines,en:plain-madeleines","Beverages and beverages preparations,Beverages,Snacks,Desserts,Sweet snacks,Biscuits and cakes,Biscuits and crackers,Biscuits,Cakes,Pound Cake,Madeleines,Plain madeleines",NaN,NaN,NaN,France,france,xxx,it:xxx,it:xxx,NaN,NaN,NaN,DE,en:germany,Germany,"Farine de blé 33%, sucre, huile de colza, œufs de poules élevées en plein air 18%, sirop de glucose-fructose, Un stabilisant : glycérol, poudres à lever : carbonates d'ammonium-carbonates de sodium - citrates de sodium (blé), sel, gluten de blé, lait écrémé en poudre, fibres végétales, arôme naturel.","en:wheat-flour,en:cereal,en:flour,en:wheat,en:cereal-flour,en:sugar,en:added-sugar,en:disaccharide,en:colza-oil,en:oil-and-fat,en:vegetable-oil-and-fat,en:rapeseed-oil,en:free-range-chicken-eggs,en:egg,en:chicken-egg,en:free-range-eggs,en:glucose-fructose-syrup,en:monosaccharide,en:fructose,en:glucose,en:stabiliser,en:raising-agent,en:e331,en:salt,en:wheat-gluten,en:gluten,en:skimmed-milk-powder,en:dairy,en:milk-powder,en:vegetable-fiber,en:fiber,en:natural-flavouring,en:flavouring,en:e422,fr:carbonates-d-ammonium-carbonates-de-sodium",3.0,NaN,"en:e331,en:e422,en:e503","E331 - Sodium citrates,E422 - Glycerol,E503 - Ammonium carbonates",NaN,unknown,Beverages,Sweetened beverages,en:sweetened-beverages,"en:beverages,en:sweetened-beverages","Beverages,Sweetened beverages",7.0,f,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,11,NaN,NaN,NaN,NaN,NaN,"Kugler, Pyrat",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en:germany,en:germany,Germany,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unknown,unknown,unknown,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,12,Besan chilla with stuffed chciken,NaN,NaN,NaN,NaN,Toneop,"Dietary supplements,Bodybuilding supplements,Groceries,Supplement","en:dietary-supplements,en:bodybuilding-supplements,en:groceries,en:supplement","Dietary supplements,Bodybuilding supplements,Groceries,Supplement",it:mondo,en:world,World,NaN,NaN,NaN,NaN,NaN,CE,ce,NaN,Germany,en:germany,Germany,NaN,NaN,NaN,NaN,NaN,NaN,NaN,not-applicable,unknown,unknown,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,13,Powdered peanut butter,pot plastique,pot-plastique,Pot-plastique,NaN,Pbfit,"Snacks, Meals, Rice dishes, Risottos, Powder peanut butter","en:snacks,en:meals,en:rice-dishes,en:risottos,en:powder-peanut-butter","Snacks,Meals,Rice dishes,Risottos,Powder-peanut-butter",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"EMB 41106C,FR 41.108.001 EC","emb-41106c,fr-41-108-001-ec","47.6,2.016667",en:Switzerland,en:switzerland,Switzerland,"Water, Leptospermum Scoparium Mel (Manuka Honey), Sodium C14-C16 Olefin Sulfonate, Cocamide DIPA , Cocamidopropyl Betaine (Coconut Oil), Cocamidopropyl Betaine (Coconut Oil), Glycereth-2 Cocoate, Melaleuca Alternifolia (Tea Tree) Leaf Oil, Malus Domestica Fruit Cell Culture Extract, Phenoxyethanol (and) Ethylhexylglycerin","en:water,en:leptospermum-scoparium-mel,en:sodium-c14-c16-olefin-sulfonate,en:cocamide-dipa,en:cocamidopropyl-betaine,en:glycereth-2-cocoate,en:melaleuca-alternifolia,en:oil,en:oil-and-fat,en:malus-domestica-fruit-cell-culture-extract,en:phenoxyethanol,en:ethylhexylglycerin,en:manuka-honey,en:added-sugar,en:honey,en:coconut-oil,en:vegetable-oil-and-fat,en:vegetable-oil,en:tea-tree",0.0,NaN,NaN,NaN,3.0,c,Composite foods,One-dish meals,en:one-dish-meals,"en:composite-foods,en:one-dish-meals","Composite foods,One-dish meals",NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,15,Madeleines ChocoLait,"Plastique, Carton","en:plastic,en:cardboard","Plastic,Cardboard",NaN,Apple bandit,"Snacks, Snacks sucrés, Biscuits et gâteaux, Gâteaux, Gâteaux au chocolat, Madeleines, Madeleines au chocolat","en:snacks,en:sweet-snacks,en:biscuits-and-cakes,en:cakes,en:chocolate-cakes,en:madeleines,en:chocolate-madeleines","Snacks,Sweet snacks,Biscuits and cakes,Cakes,Chocolate cakes,Madeleines,Chocolate madeleines",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,France,en:france,France,"Farine de blé 27%, chocolat au lait 18% (sucre, beurre de cacao, lait entier en poudre, pâte de cacao, émulsifiant : lécithines (soja), arôme naturel de vanille), sucre, huile de colza, œufs de poules élevées en plein air 14.5%, sirop de glucose-fructose, stabilisant : glycérol, poudres à lever : carbonates d'ammonium - carbonates de sodium - citrates de sodium (blé), sel, gluten de blé, lait écrémé en poudre, fibres végétales, arôme naturel. Peut contenir des traces de fruits à coque.","en:wheat-flour,en:cereal,en:flour,en:wheat,en:cereal-flour,en:milk-chocolate,en:chocolate,en:sugar,en:added-sugar,en:disaccharide,en:colza-oil,en:oil-and-fat,en:vegetable-oil-and-fat,en:rapeseed-oil,en:free-range-chicken-eggs,en:egg,en:chicken-egg,en:free-range-eggs,en:glucose-fructose-syrup,en:monosaccharide,en:fructose,en:glucose,en:stabiliser,en:raising-agent,en:e500,en:e331,en:salt,en:wheat-gluten,en:gluten,en:skimmed-milk-powder,en:dairy,en:milk-powder,en:vegetable-fiber,en:fiber,en:natural-flavouring,en:flavouring,en:cocoa-butter,en:plant,en:cocoa,en:whole-milk-powder,en:cocoa-paste,en:emulsifier,en:natural-vanilla-flavouring,en:vanilla-flavouring,en:e422,en:e503,en:e322,en:soya-lecithin,en:e322i",6.0,NaN,"en:e322,en:e322i,en:e331,en:e422,en:e500,en:e503","E322 - Lecithins,E322i - Lecithin,E331 - Sodium citrates,E422 - Glycerol,E500 - Sodium carbonates,E503 - Ammonium carbonates",20.0,e,Sugary snacks,Biscuits and cakes,en:biscuits-and-cakes,"en:sugary-snacks,en:biscuits-and-cakes","Sugary snacks,Biscuits and cakes",32.0,d,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,16,velvety vanilla cake mix,NaN,NaN,NaN,NaN,betty crocker,"Dietary supplements, Vitamins","en:dietary-supplements,en:vitamins","Dietary supplements,Vitamins",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Beef liver,"en:beef-liver,en:animal,en:beef",0.0,NaN,NaN,NaN,NaN,not-applicable,unknown,unknown,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,17,Collagen For Her,NaN,NaN,NaN,NaN,Bodylab,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Ireland, en:france","en:france,en:ireland","France,Ireland","whey protein concentrate, milk protein concentrate, flavoring, thickener (xanthan gum), sweetener (sucralose)","en:whey-protein,en:protein,en:animal-protein,en:milk-proteins,en:milk-protein-concentrate,en:flavouring,en:thickener,en:sweetener,en:e415,en:e955",2.0,NaN,"en:e415,en:e955","E415 - Xanthan gum,E955 - Sucralose",NaN,unknown,unknown,unknown,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,18,Chocolate peanut butter protein,NaN,NaN,NaN,NaN,Pays Gourmand,"Fasern,Pflanzliche Lebensmittel","en:plant-based-foods-and-beverages,en:plant-based-foods,de:fasern","Plant-based foods and beverages,Plant-based foods,de:fasern",NaN,NaN,NaN,NaN,NaN,en:nutriscore,en:nutriscore,Nutriscore,NaN,NaN,NaN,"Irland, Germany","en:germany,en:ireland","Germany,Ireland",NaN,NaN,NaN,NaN,NaN,NaN,NaN,unknown,unknown,unknown,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,19,Erdbeeren,NaN,NaN,NaN,NaN,BeerenBrüder,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en:germany,en:germany,Germany,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unknown,unknown,unknown,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,20,Nesquik moins de sucre,1 boîte en carton à recycler 50 sachets individuels à recycler,fr:1-boite-en-carton-a-recycler-50-sachets-individuels-a-recycler,fr:1-boite-en-carton-a-recycler-50-sachets-individuels-a-recycler,NaN,Nestlé,"Snacks, Snacks sucrés, Biscuits et gâteaux, Gâteaux, Quatre-quarts, Gâteaux au chocolat, Madeleines, Madeleines au chocolat","en:snacks,en:sweet-snacks,en:biscuits-and-cakes,en:cakes,en:pound-cake,en:chocolate-cakes,en:madeleines,en:chocolate-madeleines","Snacks,Sweet snacks,Biscuits and cakes,Cakes,Pound Cake,Chocolate cakes,Madeleines,Chocolate madeleines","fr:Blé origine France,fr:Œufs origine France","fr:ble-origine-france,fr:oeufs-origine-france","fr:ble-origine-france,fr:oeufs-origine-france","Saint-Yrieix,France","saint-yrieix,france","No gluten, Organic, Free range, Kosher, No preservatives, USDA Organic, Free range eggs, Green Dot, Made in France, No colorings, No palm oil, Nutriscore, Pure cocoa butter, fr:Blé français, Triman, fr:Fabriqué en Nouvelle-Aquitaine, en:nutriscore-grade-a","en:no-gluten,en:organic,en:free-range,en:kosher,en:no-preservatives,en:usda-organic,en:free-range-eggs,en:green-dot,en:made-in-france,en:no-colorings,en:no-palm-oil,en:nutriscore,en:nutriscore-grade-a,en:pure-cocoa-butter,fr:ble-francais,fr:triman,fr:fabrique-en-nouvelle-aquitaine","No gluten,Organic,Free range,Kosher,No preservatives,USDA Organic,Free range eggs,Green Dot,Made in France,No colorings,No palm oil,Nutriscore,Nutriscore Grade A,Pure cocoa butter,fr:Blé français,Triman,fr:fabrique-en-nouvelle-aquitaine",NaN,NaN,NaN,"Frankreich, Germany","en:france,en:germany","France,Germany","Nuts (Peanuts, Almonds), Prebiotic Blend (Tapioca Fiber, Vegetable Fiber), Protein Blend (Pea Protein Crisps [Pea Protein, Tapioca Starch], Pea Protein), Natural Flavors, Peanut Flour, Coconut Oil, Unsweetened Chocolate, Cocoa, Cocoa Butter, Sea Salt, Lion's Mane, Stevia Plant Extract, Vitamin E","en:nut,en:prebiotic-blend,en:protein-blend,en:natural-flavouring,en:flavouring,en:peanut-flour,en:peanut,en:coconut-oil,en:oil-and-fat,en:vegetable-oil-and-fat,en:vegetable-oil,en:chocolate,en:cocoa,en:plant,en:cocoa-butter,en:sea-salt,en:salt,en:lion-s-mane,en:stevia-plant-extract,en:vitamin-e,en:vitamins,en:almond,en:tree-nut,en:tapioca-fiber,en:vegetable-fiber,en:fiber,en:pea-protein-crisps,en:pea-protein,en:protein,en:plant-protein,en:tapioca,en:starch",0.0,NaN,NaN,NaN,NaN,unknown,Sugary snacks,Biscuits and cakes,en:biscuits-and-cakes,"en:sugary-snacks,en:biscuits-and-cakes","Sugary snacks,Biscuits and cakes",32.0,d,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,21,Inulin Prebiotic Fiber,NaN,NaN,NaN,NaN,It's Just!,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en:France,en:france,France,Inulin Prebiotic Fiber (Chicory Root Powder),"en:inulin-prebiotic-fiber,en:chicory-root,en:vegetable,en:shoot-vegetable,en:chicory",0.0,NaN,NaN,NaN,NaN,unknown,unknown,unknown,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,22,Farandole de madeleine,"Boîte en carton, Film en plastique","fr:boite-en-carton,fr:film-en-plastique","fr:boite-en-carton,fr:film-en-plastique",NaN,Coca-Cola,"Snacks, Snacks sucrés, Biscuits et gâteaux, Gâteaux, Gâteaux au chocolat, Madeleines, Madeleines au chocolat, Madeleines longues","en:snacks,en:sweet-snacks,en:biscuits-and-cakes,en:cakes,en:chocolate-cakes,en:madeleines,en:chocolate-madeleines,en:long-madeleines","Snacks,Sweet snacks,Biscuits and cakes,Cakes,Chocolate cakes,Madeleines,Chocolate madeleines,Long madeleines",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Brasil,en:brazil,Brazil,"Madeleines ChocoNoir - Madeleines nappées de chocolat noir : farine de blé 27%, chocolat noir 18% (pâte de cacao, sucre, beurre de cacao, matière grasse laitière anhydre, émulsifiant : lécithines (soja), arôme naturel de vanille), sucre, huile de colza, œufs de poules élevées en plein air 14.5%, sirop de glucose-fructose, stabilisant : glycérol, poudres à lever : carbonates d'ammonium - carbonates de sodium - citrates de sodium (blé), sel, gluten de blé, lait écrémé en poudre, fibres végétales, arôme naturel. Peut contenir des traces de fruits à coque. Toutes vos remarques et suggestions sont les bienvenues : contactez notre Service Qualité en indiquant le nom et le numéro du lot du produit concerné figurant sur le dessus de la boîte. Pour conserver toutes les qualités de ce produit, le maintenir dans un milieu tempéré à l'abri de la chaleur, de l'humidité et du froid.","fr:madeleines-choconoir,fr:madeleines-nappees-de-chocolat-noir,en:dark-chocolate,en:chocolate,en:sugar,en:added-sugar,en:disaccharide,en:colza-oil,en:oil-and-fat,en:vegetable-oil-and-fat,en:rapeseed-oil,en:free-range-chicken-eggs,en:egg,en:chicken-egg,en:free-range-eggs,en:glucose-fructose-syrup,en:monosaccharide,en:fructose,en:glucose,en:stabiliser,en:raising-agent,en:e500,en:e331,en:salt,en:wheat-gluten,en:gluten,en:skimmed-milk-powder,en:dairy,en:milk-powder,en:vegetable-fiber,en:fiber,en:natural-flavouring,en:flavouring,fr:toutes-vos-remarques-et-suggestions-sont-les-bienvenues,fr:le-maintenir-dans-un-milieu-tempere-a-l-abri-de-la-chaleur,fr:de-l-humidite-et-du-froid,en:wheat-flour,en:cereal,en:flour,en:wheat,en:cereal-flour,en:cocoa-paste,en:plant,en:cocoa,en:cocoa-butter,fr:matiere-grasse-de-lait-anhydre,en:emulsifier,en:natural-vanilla-flavouring,en:vanilla-flavouring,en:e422,en:e503,fr:contactez-notre-service-qualite-en-indiquant-le-nom-et-le-numero-du-lot-du-produit-concerne-figurant-sur-le-dessus-de-la-boite,fr:pour-conserver-toutes-les-qualites-de-ce-produit,en:e322,en:soya-lecithin,en:e322i",6.0,NaN,"en:e322,en:e322i,en:e331,en:e422,en:e500,en:e503","E322 - Lecithins,E322i - Lecithin,E331 - Sodium citrates,E422 - Glycerol,E500 - Sodium carbonates,E503 - Ammonium carbonates",9.0,c,Sugary snacks,Biscuits and cakes,en:biscuits-and-cakes,"en:sugary-snacks,en:biscuits-and-cakes","Sugary snacks,Biscuits and cakes",41.0,d,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en:Germany,en:germany,Germany,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

:

:

In [ ]:
import pandas as pd
import numpy as np
import os

# Créer le dossier data s'il n'existe pas
os.makedirs("data", exist_ok=True)

# Colonnes à garder
nutriscore_cols = [
    "code",
    "energy-kj_100g",
    "sugars_100g",
    "saturated-fat_100g",
    "sodium_100g",
    "salt_100g",
    "fiber_100g",
    "proteins_100g",
    "fruits-vegetables-legumes_100g"
]

ecoscore_cols = [
    "code",
    "categories",
    "categories_tags",
    "main_category",
    "main_category_en",
    "labels",
    "labels_tags",
    "origins",
    "origins_tags",
    "countries",
    "countries_tags",
    "manufacturing_places",
    "ingredients_text",
    "ingredients_tags",
    "packaging",
    "packaging_tags",
    "packaging_text"
]

# Garder seulement les colonnes existantes
df_nutriscore = df[[c for c in nutriscore_cols if c in df.columns]].copy()
df_ecoscore = df[[c for c in ecoscore_cols if c in df.columns]].copy()

# Sauvegarde dans le dossier data
df_nutriscore.to_csv("data/dataset_nutriscore.csv", index=False)
df_ecoscore.to_csv("data/dataset_ecoscore.csv", index=False)

:

:

In [4]:
import pandas as pd

nutriscore_cols = [
    "code",
    "energy-kj_100g",
    "sugars_100g",
    "saturated-fat_100g",
    "sodium_100g",
    "salt_100g",
    "fiber_100g",
    "proteins_100g",
    "fruits-vegetables-legumes_100g",
]

chunk_iter = pd.read_csv(
    path,
    sep="\t",
    encoding="utf-8",
    chunksize=50000,
    low_memory=False,
    on_bad_lines="skip",
)

filtered_chunks = []

for chunk in chunk_iter:
    cols_presentes = [c for c in nutriscore_cols if c in chunk.columns]
    if not cols_presentes:
        continue

    # Considerer les valeurs vides comme manquantes
    nutri_view = chunk[cols_presentes].replace(r"^\s*$", pd.NA, regex=True)
    mask = nutri_view.notna().any(axis=1)
    filtered_chunks.append(chunk.loc[mask])

if filtered_chunks:
    df_rows_avec_nutriscore = pd.concat(filtered_chunks, ignore_index=True)
else:
    df_rows_avec_nutriscore = pd.DataFrame()

print(f"Nombre de lignes retenues: {len(df_rows_avec_nutriscore):,}")
print(f"Nombre de colonnes conservees: {df_rows_avec_nutriscore.shape[1]}")

df_rows_avec_nutriscore.head()

C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (11,17,34,36) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (11,17,34,36,47) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (34,36) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (11,17,34,36,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (32,33,34,36) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (11,17,34,36,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (17,34,36,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (17,32,33,34,36,54) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (11,14,15,16,17,24,25,26,27,28,34,36,52,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (17,34,36) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (12,17,32,33,34,36,37,52,68,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (17,34) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (11,17,52) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (17,34,36) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (17,34,36) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (11,17,34,36) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (34,36,52) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (17,32,33,34,36) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (17,32,33,34,36) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (17,32,33,34,36,52) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (17,34,36) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,54) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,54,68,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (17,54,68,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (68) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (68,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,17,68) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (17,45,47,48,49,55,56,68) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (11,54,68) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (54,68) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,54,68) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,54,68) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (11,68) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (11,68) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (11,54,68) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,35,46,51,53,54,57,68) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,35,51,52,53,54,68) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,54,68) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,54,68) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (11,68) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,68) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,34,36,68,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,34,36,54,68,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,34,36,54,68,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,68,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,34,36,68,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,34,36,54,68) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,34,36,68,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (11,34,36,68,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,32,33,34,36,54,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,34,36,54,68,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,34,36,68,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,34,36,68,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,17,34,36,68,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,17,68) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,34,36) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,34,36,68,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,17,34,36,54,68,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,34,36,68,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (11,17,34,36,68) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,34,36,68,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,34,36,68) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,34,36,54,68,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,34,36,68,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (34,36,68,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,34,36,54,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,17,34,36,68,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,34,36,54) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,34,36,68,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,17,34,36,68,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (11,34,36) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,17,34,36,68,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,34,36,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,17,34,36,54,68) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,17,34,36,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,34,36,68,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,34,36,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,34,36,68,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,34,36,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,17,34,36) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,11,34,36,68,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (0,12,32,33,34,36,68,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:
C:\Users\mulle\AppData\Local\Temp\ipykernel_4188\1617982732.py:26: DtypeWarning: Columns (11,34,36,54,68,73) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in chunk_iter:

Nombre de lignes retenues: 4,398,741
Nombre de colonnes conservees: 209

,code,url,creator,created_t,created_datetime,last_modified_t,last_modified_datetime,last_modified_by,last_updated_t,last_updated_datetime,...,water-hardness_100g,choline_100g,phylloquinone_100g,beta-glucan_100g,inositol_100g,carnitine_100g,sulphate_100g,nitrate_100g,acidity_100g,carbohydrates-total_100g
0,2,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1760861583,2025-10-19T08:13:03Z,1760861586,2025-10-19T08:13:06Z,NaN,1.760862e+09,2025-10-19T08:13:06Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1752485388,2025-07-14T09:29:48Z,1752485389,2025-07-14T09:29:49Z,NaN,1.752485e+09,2025-07-14T09:29:49Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1768903196,2026-01-20T09:59:56Z,1768903204,2026-01-20T10:00:04Z,NaN,1.768903e+09,2026-01-20T10:00:04Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5,http://world-en.openfoodfacts.org/product/0000...,moon-rabbit,1767072228,2025-12-30T05:23:48Z,1767072233,2025-12-30T05:23:53Z,moon-rabbit,1.767072e+09,2025-12-30T05:23:53Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6,http://world-en.openfoodfacts.org/product/0000...,moon-rabbit,1760212975,2025-10-11T20:02:55Z,1760218930,2025-10-11T21:42:10Z,ascharao,1.760219e+09,2025-10-11T21:42:10Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
import os
from IPython.display import FileLink

os.makedirs("data", exist_ok=True)
output_path = "data/dataset_nutriscore_rows_avec_data.csv"

df_rows_avec_nutriscore.to_csv(output_path, index=False)
print(f"Fichier enregistre: {output_path}")

FileLink(output_path)

KeyboardInterrupt: